#!/bin/bash

# CAREFULL! LATEST RELEASE IS NOT EVERYTIME THE STABLE VERSION!

#Variables
paperversion="1.17.1"
outputfolder="/tmp/"
outputfilename="paper-$paperversion-$number.jar"
# If you wanna change the Output Filename to paper.jar just use output-filename="paper.jar"

#Script Magic

# Search for latest Number
number=$(curl https://papermc.io/api/v2/projects/paper/versions/$paperversion/ |sed 's/.*builds//' | grep -o '[0-9]*' | sort -nr | head -1)

#Download Latest Release
curl "https://papermc.io/api/v2/projects/paper/versions/$paperversion/builds/$number/downloads/paper-$paperversion-$number.jar" -o "$outputfolder/$outputfilename"
